package com.github.wire.enums

enum class UpdateType {
    MESSAGE,
    EDITED_MESSAGE,
    CALLBACK_QUERY,
    INLINE_QUERY,
    SHIPPING_QUERY,
    PRE_CHECKOUT_QUERY,
    CHOSEN_INLINE_RESULT,
    CHANNEL_POST,
    EDITED_CHANNEL_POST,
    UNKNOWN
}